# ------------------------------------------------Environment Settings------------------------------------------------#
gpu_id: "0,1,2,3,4,5,6,7"

# -------------------------------------------------Retrieval Settings------------------------------------------------#
# If set the name, the model path will be find in global paths
retrieval_method: "llamaindex/vdr-2b-v1"  # name or path of the retrieval model.
index_path: "/scratch-scc/projects/scc_ulsb_fe/yang/images_index/vdr-2b-v1_Flat.index" # path to the indexed file
faiss_gpu: False # whether use gpu to hold index
corpus_path: "/scratch-scc/projects/scc_ulsb_fe/yang/images_corpus/images.parquet"  # path to corpus in '.jsonl' format that store the documents
use_sentence_transformer: True



